"""paideia tokenomics

Revision ID: 028c52b0d196
Revises: 2f030ff38600
Create Date: 2022-11-21 09:49:42.050699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '028c52b0d196'
down_revision = '2f030ff38600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('market', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('ohlc')

